# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/erick/Documents/GitHub/460M-HDL-Design/project_5/B/460M_Lab5/460M_Lab5.cache/wt [current_project]
set_property parent.project_path C:/Users/erick/Documents/GitHub/460M-HDL-Design/project_5/B/460M_Lab5/460M_Lab5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/erick/Documents/GitHub/460M-HDL-Design/project_5/B/460M_Lab5/460M_Lab5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/erick/Documents/GitHub/460M-HDL-Design/project_5/B/460M_Lab5/460M_Lab5.srcs/sources_1/new/Screen_Driver.v
  C:/Users/erick/Documents/GitHub/460M-HDL-Design/project_5/B/460M_Lab5/460M_Lab5.srcs/sources_1/new/VGA.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/erick/Documents/GitHub/460M-HDL-Design/project_5/B/460M_Lab5/460M_Lab5.srcs/constrs_1/imports/Labs/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/erick/Documents/GitHub/460M-HDL-Design/project_5/B/460M_Lab5/460M_Lab5.srcs/constrs_1/imports/Labs/Basys3_Master.xdc]


synth_design -top VGA -part xc7a35tcpg236-1


write_checkpoint -force -noxdef VGA.dcp

catch { report_utilization -file VGA_utilization_synth.rpt -pb VGA_utilization_synth.pb }
